### ISSUE TITLE
Login view not loading

### ISSUE THREAD

**Issue by nnguyenn** [EthanHaque/recalpp#47]
https://github.com/EthanHaque/recalpp/blob/5c8721c4cd9d74b893264977e68a06a6ab173393/recalpp/server/recalpp_server/urls.py#L21-L26

I'm trying to run the webapp locally and it directs me to schedule_builder instead of login. Then when I try to manually change the URL by replacing schedule_builder/ with login/ it says error 404 page not found, and I'm unsure where the issue is.

**Comment by EthanHaque** [comment]
Fixed. Check out the changes and look at the other apps in the project to see why the changes were necessary
